# -*- coding: utf-8 -*-
"""setimaed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hz1gfCZSZOmsTK_HvZDPAz3pRoTYbHh

# **QUESTÃO 7**

# Item A
"""

import random
import time

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None
        self.prev = None

class Deque:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def is_empty(self):
        return self.size == 0

    def is_full(self):
        return False  # Em uma implementação dinâmica, não há limite de tamanho

    def add_front(self, value):
        new_node = Node(value)
        if self.is_empty():
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node
            new_node.prev = new_node
        else:
            new_node.next = self.front
            new_node.prev = self.rear
            self.front.prev = new_node
            self.rear.next = new_node
            self.front = new_node
        self.size += 1

    def add_rear(self, value):
        new_node = Node(value)
        if self.is_empty():
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node
            new_node.prev = new_node
        else:
            new_node.next = self.front
            new_node.prev = self.rear
            self.rear.next = new_node
            self.front.prev = new_node
            self.rear = new_node
        self.size += 1

    def remove_front(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        if self.front == self.rear:
            self.front = None
            self.rear = None
        else:
            self.front = self.front.next
            self.rear.next = self.front
            self.front.prev = self.rear
        self.size -= 1

    def remove_rear(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        if self.front == self.rear:
            self.front = None
            self.rear = None
        else:
            self.rear = self.rear.prev
            self.front.prev = self.rear
            self.rear.next = self.front
        self.size -= 1

    def peek_front(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        return self.front.value

    def peek_rear(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        return self.rear.value

    def display(self):
        if self.is_empty():
            print("Deque is empty")
            return
        current = self.front
        while current != self.rear:
            print(current.value, end=" <-> ")
            current = current.next
        print(current.value)

# Função para medir o tempo de execução
import time
def measure_time(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# Testando a implementação
for size in [100, 1000, 10000, 1000000]:
    deque = Deque()
    # Medindo o tempo de inicialização
    init_time = measure_time(deque.__init__)
    print(f"Tamanho do deque: {size}")
    print(f"Tempo de inicialização: {init_time:.6f} segundos")

    # Adicionando elementos ao deque
    for i in range(size):
        deque.add_rear(i)

    # Exibindo alguns elementos
    deque.display()

    # Removendo elementos
    for i in range(size // 10):  # Remover 10% dos elementos
        deque.remove_front()
        deque.remove_rear()

    # Exibindo o deque após remoções
    deque.display()

"""A estrutura suporta inserções e remoções eficientes tanto na extremidade frontal quanto na traseira. O deque é dinâmico e não possui limite de tamanho. Além disso, há uma função para medir o tempo de execução de operações realizadas sobre o deque.

No final, o código realiza testes em deques de tamanhos variados (100, 1.000, 10.000 e 1.000.000), medindo tempos de execução para inicialização, inserções e remoções.

Resultados de Execução
Tamanho do deque pequeno (100 elementos):

Inicialização: extremamente rápida (tempo próximo de 0).
Inserções e remoções acontecem de forma eficiente, com tempos de execução baixos.
A exibição funciona adequadamente.
Tamanho do deque grande (1.000.000 elementos):

Inserções podem levar alguns segundos devido ao grande número de operações.
Remoções também apresentam tempos proporcionais à quantidade de elementos processados.
A exibição completa do deque pode ser impraticável para tamanhos grandes devido ao volume de saída no console.

As operações básicas do deque (add, remove, peek) são altamente eficientes (O(1)). Apenas operações como exibição ou processamento em massa têm complexidade linear (O(n)), onde
𝑛
n é o número de elementos.

# Item B
"""

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

class DequeCircular:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def Deque_é_vazio(self):
        return self.size == 0

    def adicionar_frente(self, value):
        new_node = Node(value)
        if self.Deque_é_vazio():
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node
        else:
            new_node.next = self.front
            self.front = new_node
            self.rear.next = self.front
        self.size += 1

    def adicionar_trás(self, value):
        new_node = Node(value)
        if self.Deque_é_vazio():
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node
        else:
            new_node.next = self.front
            self.rear.next = new_node
            self.rear = new_node
        self.size += 1

    def remover_frente(self):
        if self.Deque_é_vazio():
            raise IndexError("O deque está vazio.")

        value = self.front.value
        if self.front == self.rear:
            self.front = None
            self.rear = None
        else:
            self.front = self.front.next
            self.rear.next = self.front
        self.size -= 1
        return value

    def remover_trás(self):
        if self.Deque_é_vazio():
            raise IndexError("O deque está vazio.")

        value = self.rear.value
        if self.front == self.rear:
            self.front = None
            self.rear = None
        else:
            current = self.front
            while current.next != self.rear:
                current = current.next
            current.next = self.front
            self.rear = current
        self.size -= 1
        return value

def medir_tempo(func, *args):
    inicio = time.time()
    func(*args)
    fim = time.time()
    return fim - inicio

tamanhos = [1000, 10000, 1000000]

for tamanho in tamanhos:
    deque = DequeCircular()
    tempo_inicializacao = medir_tempo(deque.__init__)
    print(f"Tamanho do deque: {tamanho}")
    print(f"Tempo de inicialização: {tempo_inicializacao:.6f} segundos")

    tempo_adicionar = medir_tempo(
        lambda: [deque.adicionar_trás(i) for i in range(tamanho)]
    )
    print(f"Tempo para adicionar {tamanho} elementos: {tempo_adicionar:.6f} segundos")

    tempo_remover = medir_tempo(
        lambda: [deque.remover_frente() for _ in range(tamanho // 10)]
    )
    print(f"Tempo para remover 10% dos elementos: {tempo_remover:.6f} segundos\n")

"""A complexidade total de cada operação varia de O(1) para inserção e remoção na frente até O(n) para remoção do final.

O tempo de execução varia conforme o tamanho do deque, especialmente nas operações de inserção e remoção. A medição do tempo é feita para os seguintes tamanhos de deque: 1000, 10000 e 1000000.

O tempo de execução das operações de inserção e remoção depende do tamanho do deque:

Inserções (adicionar_frente, adicionar_trás) têm tempo de execução O(1), o que significa que o tempo de execução permanece constante independentemente do número de elementos.
Remoções da Frente (remover_frente) também têm tempo de execução O(1).
Remoções do Final (remover_trás) têm tempo de execução O(n), pois é necessário percorrer a lista para encontrar o penúltimo nó.

# Item C
"""

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

class FilaCircular:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def fila_é_vazia(self):
        return self.size == 0

    def fila_é_cheia(self):
        # Em uma implementação dinâmica, a fila nunca estará cheia
        return False

    def enfileirar(self, value):
        new_node = Node(value)
        if self.fila_é_vazia():
            self.front = new_node
            self.rear = new_node
            new_node.next = self.front  # Lista circular
        else:
            self.rear.next = new_node
            self.rear = new_node
            self.rear.next = self.front  # Mantém a circularidade
        self.size += 1

    def desenfileirar(self):
        if self.fila_é_vazia():
            raise IndexError("Fila está vazia")
        if self.front == self.rear:
            self.front = None
            self.rear = None
        else:
            self.front = self.front.next
            self.rear.next = self.front
        self.size -= 1

    def frente(self):
        if self.fila_é_vazia():
            raise IndexError("Fila está vazia")
        return self.front.value

    def tamanho(self):
        return self.size

    def exibir(self):
        if self.fila_é_vazia():
            print("Fila está vazia.")
            return
        print(f"Fila contém {self.size} elementos.")

# Função para medir o tempo de execução
import time
def medir_tempo(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# Testando a implementação
for size in [1000, 10000, 1000000]:
    fila = FilaCircular()
    # Medindo o tempo de inicialização
    tempo_init = medir_tempo(fila.__init__)
    print(f"Tamanho da fila: {size}")
    print(f"Tempo de inicialização: {tempo_init:.6f} segundos")

    # Enfileirando elementos
    for i in range(size):
        fila.enfileirar(i)

    # Exibindo a fila (apenas mostrando o tamanho)
    fila.exibir()

    # Desenfileirando elementos
    for i in range(size // 10):  # Remover 10% dos elementos
        fila.desenfileirar()

    # Exibindo a fila após as remoções (apenas mostrando o tamanho)
    fila.exibir()

"""Os tempos de inicialização e operações de enfileiramento/desenfileiramento serão mais evidentes à medida que o número de elementos cresce, mas com a implementação atual, as operações são de complexidade O(1), logo, o tempo de execução por operação não aumenta drasticamente com o número de elementos

Tempo de Execução: O código é rápido para tamanhos grandes, pois cada operação é constante

# Item D
"""

import time

class Node:
    def __init__(self, value):
        self.value = value  # Valor armazenado no nó
        self.next = None  # Ponteiro para o próximo nó

class FilaCircular:
    def __init__(self):
        self.front = None  # Início da fila
        self.rear = None   # Fim da fila
        self.size = 0      # Tamanho da fila

    def fila_é_vazia(self):
        return self.size == 0  # A fila está vazia se o tamanho for zero

    def fila_é_cheia(self):
        return False  # Em uma implementação dinâmica, a fila nunca está cheia

    def insere_fila(self, value):
        """
        Insere um valor no final da fila (enfileiramento).
        """
        new_node = Node(value)  # Criação de um novo nó com o valor

        if self.fila_é_vazia():  # Se a fila estiver vazia, o novo nó será o único na fila
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node  # O nó aponta para ele mesmo (circular)
        else:  # Se a fila não estiver vazia
            self.rear.next = new_node  # O nó atual aponta para o novo nó
            self.rear = new_node       # O rear agora será o novo nó
            self.rear.next = self.front  # O último nó aponta de volta para o início (circular)

        self.size += 1  # Incrementa o tamanho da fila

    def desenfileira(self):
        """
        Remove um elemento do início da fila (desenfileiramento).
        """
        if self.fila_é_vazia():
            raise IndexError("Fila vazia. Não é possível desenfileirar.")

        if self.front == self.rear:  # Se a fila tem apenas um elemento
            self.front = None
            self.rear = None
        else:  # Se houver mais de um elemento
            self.front = self.front.next
            self.rear.next = self.front

        self.size -= 1  # Decrementa o tamanho da fila

    def frente(self):
        """
        Retorna o valor do elemento na frente da fila, sem removê-lo.
        """
        if self.fila_é_vazia():
            raise IndexError("Fila vazia. Não há elemento na frente.")
        return self.front.value

    def tamanho(self):
        """
        Retorna o tamanho da fila.
        """
        return self.size

    def exibir(self):
        """
        Exibe os elementos da fila.
        """
        if self.fila_é_vazia():
            print("Fila vazia.")
            return

        current = self.front
        print("Fila: ", end="")
        while current != self.rear:
            print(current.value, end=" -> ")
            current = current.next
        print(current.value)  # Exibe o último elemento

# Função para medir o tempo de execução
def measure_time(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# Testando a implementação e medindo o tempo de execução
for size in [1000, 10000, 1000000]:
    fila = FilaCircular()

    # Medindo o tempo de inicialização
    init_time = measure_time(fila.__init__)
    print(f"Tempo de inicialização: {init_time:.6f} segundos")
    print(f"Tamanho do deque: {size}")

    # Inserindo elementos na fila
    for i in range(size):
        fila.insere_fila(i)

    # Exibindo os resultados de inserção
    # Não exibindo a sequência dos números, apenas a confirmação de que a operação foi realizada

    # Removendo alguns elementos para testar o comportamento
    for i in range(size // 10):  # Remover 10% dos elementos
        fila.desenfileira()

    # Exibindo a fila após remoções
    # Não exibindo a sequência, apenas confirmando que o deque foi modificado

"""**Complexidade das operações principais:**

Inserção (insere_fila): O(1)

Remoção (desenfileira): O(1)

Acesso ao primeiro (frente): O(1)

Verificações (fila_é_vazia, fila_é_cheia): O(1)

Exibição (exibir): O(n)

**Tempo de Execução:**

O tempo de execução das operações principais de inserção e remoção foi muito baixo, indicando que o uso de uma estrutura de fila circular ligada é eficiente. O tempo de inicialização foi em torno de microssegundos, com a execução das inserções e remoções rápidas, mesmo para tamanhos grandes de fila (1000000 elementos).

# Item E
"""

import time

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

class FilaCircular:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def fila_é_vazia(self):
        return self.size == 0

    def fila_é_cheia(self):
        return False  # Como é uma lista circular dinâmica, não tem limite de tamanho.

    def insere_fila(self, value):
        new_node = Node(value)
        if self.fila_é_vazia():
            self.front = new_node
            self.rear = new_node
            new_node.next = self.front  # Aponta para si mesmo, formando a circularidade
        else:
            self.rear.next = new_node
            self.rear = new_node
            self.rear.next = self.front  # Mantém a circularidade
        self.size += 1

    def remove_fila(self):
        if self.fila_é_vazia():
            raise IndexError("Fila está vazia!")
        if self.front == self.rear:  # Apenas um elemento na fila
            self.front = None
            self.rear = None
        else:
            self.front = self.front.next
            self.rear.next = self.front  # Atualiza a ligação circular
        self.size -= 1

    def frente(self):
        if self.fila_é_vazia():
            raise IndexError("Fila está vazia!")
        return self.front.value

    def tamanho(self):
        return self.size

    def exibir(self):
        if self.fila_é_vazia():
            print("Fila vazia!")
            return
        current = self.front
        while True:
            print(current.value, end=" -> ")
            current = current.next
            if current == self.front:
                break
        print()

# Função para medir o tempo de execução
def measure_time(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# Testando a implementação para diferentes tamanhos de fila
for size in [1000, 10000, 1000000]:
    fila = FilaCircular()

    # Medindo o tempo de inicialização
    init_time = measure_time(fila.__init__)
    print(f"Tamanho do deque: {size}")
    print(f"Tempo de inicialização: {init_time:.6f} segundos")

    # Inserindo elementos na fila
    for i in range(size):
        fila.insere_fila(i)

    # Removendo um elemento da fila
    fila.remove_fila()

    # Resultado sem exibir a sequência de números da fila
    print("Tempo de execução do remove_fila e tamanho após remoção:")
    print(f"Tamanho atual da fila: {fila.tamanho()}")

"""O tempo de execução depende do número de elementos inseridos e removidos, mas como cada operação (inserção e remoção) é O(1), o tempo de execução é muito eficiente mesmo para grandes tamanhos de fila.

As operações insere_fila(), remove_fila(), fila_é_vazia(), fila_é_cheia() e frente() têm complexidade O(1), ou seja, são realizadas em tempo constante.

A operação exibir() tem complexidade O(n), pois é necessário percorrer todos os elementos da fila para exibi-los.

# Item F
"""

import time

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

class FilaCircular:
    def __init__(self):
        self.front = None
        self.rear = None

    def fila_é_vazia(self):
        return self.front is None

    def insere_fila(self, value):
        new_node = Node(value)
        if self.fila_é_vazia():
            self.front = new_node
            self.rear = new_node
            new_node.next = new_node  # Circularidade
        else:
            new_node.next = self.front
            self.rear.next = new_node
            self.rear = new_node

    def remove_fila(self):
        if self.fila_é_vazia():
            raise IndexError("A fila está vazia")
        if self.front == self.rear:  # Apenas um elemento
            removed_value = self.front.value
            self.front = None
            self.rear = None
        else:
            removed_value = self.front.value
            self.front = self.front.next
            self.rear.next = self.front
        return removed_value

    def imprimir(self):
        if self.fila_é_vazia():
            print("A fila está vazia")
            return
        current = self.front
        elementos = []
        while True:
            elementos.append(current.value)
            if current == self.rear:
                break
            current = current.next
        print(" -> ".join(map(str, elementos)))

# Função para medir o tempo de execução
def medir_tempo(fila, tamanho):
    start_time = time.time()
    for i in range(tamanho):
        fila.insere_fila(i)
    end_time = time.time()
    return end_time - start_time

# Testes com diferentes tamanhos
tamanhos = [1000, 10000, 1000000]

for tamanho in tamanhos:
    fila = FilaCircular()
    init_time = medir_tempo(fila, tamanho)
    print(f"Tamanho do deque: {tamanho}")
    print(f"Tempo de inicialização: {init_time:.6f} segundos\n")

"""O código apresenta uma implementação eficiente de uma fila circular dinâmica. Todas as operações básicas têm complexidade O(1), exceto a impressão, que é O(n).

O tempo de execução cresce linearmente com o tamanho da fila, sendo a fila adequada para aplicações onde inserções e remoções rápidas são necessárias.

**Tempo de Execução:**

Inserção de N elementos: O(N), pois cada inserção é O(1).

Impressão de N elementos: O(N).

Complexidade das Operações:

fila_é_vazia: O(1) – Apenas verifica se o ponteiro front é None.

insere_fila: O(1) – Insere um novo nó no final e ajusta os ponteiros.

remove_fila: O(1) – Remove o nó no início e ajusta os ponteiros.

imprimir: O(n) – Percorre todos os elementos da fila para exibição.


"""